dependencies {
    api project(":secrets-manager-api")
    implementation 'software.amazon.awssdk:secretsmanager'
    implementation 'software.amazon.awssdk:sts'
    implementation 'io.projectreactor.addons:reactor-extra:3.6.1'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'
    implementation 'io.projectreactor:reactor-core:3.8.7'
    testImplementation 'io.projectreactor:reactor-test:3.8.7'
    implementation platform('software.amazon.awssdk:bom:2.54.1')
}

ext {
    artifactId = 'aws-secrets-manager-async'
    artifactDescription = 'Secrets Manager'
}